language: python
python:
 - "3.6.1"
# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# Run tests
script:
  - coverage run --source='.' manage.py test && coverage report
after_success:
  - coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database ecommerce_test;' -U postgres
addons:
  postgresql: "9.6"
