# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_auto_20180130_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('user', 'name')]),
        ),
    ]
